### ISSUE TITLE
Blurry text with custom color

### ISSUE THREAD

**Issue by alohasoftworks** [srgtuszy/MTLabel#19]
Interesting issue. If I use any of the standard colors (ie [UIColor blackColor]) I get crisp, good looking text. However, using an RGB color (ie [UIColor colorWithRed:49/255.0f green:54/255.0f blue:57/255.0f alpha:1]) causes blurry text:

Example:
https://www.evernote.com/shard/s14/sh/e1f5cfa3-ba4e-4df6-9b5a-8b2beaa51e47/18b15ce60f4da5cce28df955ef762eeb

**Comment by denis-kutlubaev** [comment]
I have the same problem. I use my own colors and the label is blurred.

**Comment by MarcoSero** [comment]
Me too

**Comment by MaximillionMai** [comment]
in MTLabel.m, function: - (void)drawRect:(CGRect)rect
Change the line below from:
CGContextSetShadowWithColor(context, CGSizeMake(self.shadowOffset, self.shadowOffset), 5, colorRef);
to 
CGContextSetShadowWithColor(context, CGSizeMake(self.shadowOffset, self.shadowOffset), 0, colorRef);
In other words, change that blur parameter from 5 to 0.  If the code owner comes back to the project, please fix it.

**Comment by tobiasgemperli** [comment]
Great thanks for the fix
