### ISSUE TITLE
ld linker error

### ISSUE THREAD

**Issue by dylansm** [srgtuszy/MTLabel#5]
I'm working on a project that already uses CoreText and I'm getting a nasty ld linker error in Xcode 4 when I add the header and implementation files. They look like this:

ld: duplicate symbol _CTLineGetTypographicBoundsAsRect in /Users/dylan/Library/Developer/Xcode/DerivedData/unstuck-aqkbmvbxmfrwxcflssycdwtilkfl/Build/Intermediates/unstuck.build/Debug-iphonesimulator/unstuck.build/Objects-normal/i386/MTLabel.o and /Users/dylan/Library/Developer/Xcode/DerivedData/unstuck-aqkbmvbxmfrwxcflssycdwtilkfl/Build/Intermediates/unstuck.build/Debug-iphonesimulator/unstuck.build/Objects-normal/i386/OHAttributedLabel.o for architecture i386
Command /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang failed with exit code 1

Any thoughts?

**Comment by gon** [comment]
I get the same, tried applying some of the solutions here http://stackoverflow.com/questions/4915953/upgrading-to-xcode-4-error-no-architectures-to-compile-for but so far no luck!

**Comment by gon** [comment]
Solution is here http://stackoverflow.com/questions/4419283/linker-cant-find-ctfontcreatewithnameandoptions

Cheers,
Gon

**Comment by dylansm** [comment]
Thanks for finding that, Gon.
